### ISSUE TITLE
electron-builder": Error

### ISSUE THREAD

**Issue by bayareawebpro** [kisese/adonisjs-electron#2]
Any tips to get a working app build?  I've got it working in dev mode but not as an actual app.

Using  "electron-builder": "^19.33.0"

Looks like it can't find the (.env) file or the right modules once an actual app is compiled:

{ Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.config (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/adonis/node_modules/dotenv/lib/main.js:30:37)
    at new Env (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/adonis/node_modules/adonis-framework/src/Env/index.js:30:12)
    at Object.closure (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/adonis/node_modules/adonis-framework/providers/EnvProvider.js:17:14)
    at Object.Ioc._resolveProvider (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/adonis/node_modules/adonis-fold/src/Ioc/index.js:124:53)
    at Object.Ioc.use (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/adonis/node_modules/adonis-fold/src/Ioc/index.js:376:18)
    at Ioc.use (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/adonis/node_modules/adonis-fold/src/Ioc/index.js:380:18) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
Error: Cannot find module '../../examples/config'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/adonis/node_modules/adonis-websocket/src/Ws/index.js:17:23)
    at Object.<anonymous> (/Users/builder/Downloads/adonisjs-electron-master/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/adonis/node_modules/adonis-websocket/src/Ws/index.js:129:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by hanandika** [comment]
add new .env file on root

HOST=localhost
PORT=3333
APP_KEY=n96M1TPG821EdN4mMIjnGKxGytx9W2UJ
NODE_ENV=development
CACHE_VIEWS=false
SESSION_DRIVER=cookie
DB_CONNECTION=sqlite
DB_HOST=127.0.0.1
DB_PORT=
DB_USER=root
DB_PASSWORD=
DB_DATABASE=adonis

**Comment by bayareawebpro** [comment]
That doesn't work because the when you compile the binary for a distributable app you don't have access to the file system anymore its an archive.  Gave up an moved on to other things unfortunately.
