### ISSUE TITLE
error on adonis with electron

### ISSUE THREAD

**Issue by ghost** [kisese/adonisjs-electron#4]
Uncaught Exception:
Error: listen EADDRINUSE 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1492:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:55:10)

**Comment by ghost** [comment]
HTTPS: https://gitlab.com/somkundu1989/adonis-electron.git
SSH: git@gitlab.com:somkundu1989/adonis-electron.git

Error:: Output window opening still error appears.

$ npm start

> electron-quick-start@1.0.0 start /data/html/electron-quick-start
> electron .

info: serving app on http://localhost:8000
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1492:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:55:10)
